# Generated by Django 3.2.16 on 2022-11-25 12:23

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('landmarks', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='CelebrityItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=True, verbose_name='опубликовано')),
                ('name', models.CharField(help_text='максимально 150 символов', max_length=150, verbose_name='имя')),
                ('surname', models.CharField(help_text='максимально 150 символов', max_length=150, verbose_name='фамилия')),
                ('patronymic', models.CharField(help_text='максимально 150 символов', max_length=150, verbose_name='отчество')),
                ('text', tinymce.models.HTMLField(help_text='введите ваш текст', verbose_name='описание')),
                ('landmark', models.ManyToManyField(to='landmarks.LandmarkItem', verbose_name='теги')),
            ],
            options={
                'verbose_name': 'знаменитость',
                'verbose_name_plural': 'знаменитости',
            },
        ),
        migrations.CreateModel(
            name='CelebrityItemPreview',
            fields=[
                ('upload', models.ImageField(help_text='загрузите картинку', upload_to='uploads/preview/%Y/%m', verbose_name='картинка')),
                ('celebrity', models.OneToOneField(help_text='выберете знаменитость', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='celebrities.celebrityitem', verbose_name='знаменитость')),
            ],
            options={
                'verbose_name': 'фотографию знаменитости',
                'verbose_name_plural': 'превьюшки знаменитостей',
            },
        ),
        migrations.CreateModel(
            name='CelebrityItemGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.ImageField(help_text='загрузите картинку', upload_to='uploads/gallery/%Y/%m', verbose_name='картинка')),
                ('celebrity', models.ForeignKey(help_text='выберете знаменитость', on_delete=django.db.models.deletion.CASCADE, to='celebrities.celebrityitem', verbose_name='знаменитость')),
            ],
            options={
                'verbose_name': 'фотографию знаменитости',
                'verbose_name_plural': 'фотогалерея знаменитостей',
            },
        ),
    ]
