# Generated by Django 3.2.16 on 2022-11-25 12:24

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LandmarkItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=True, verbose_name='опубликовано')),
                ('name', models.CharField(help_text='максимально 150 символов', max_length=150, verbose_name='имя')),
                ('text', tinymce.models.HTMLField(help_text='введите ваш текст', verbose_name='описание')),
                ('link', models.CharField(help_text='максимально 150 символов', max_length=150, verbose_name='ссылка')),
            ],
            options={
                'verbose_name': 'достопримечательность',
                'verbose_name_plural': 'достопримечательности',
            },
        ),
        migrations.CreateModel(
            name='LandmarkItemPreview',
            fields=[
                ('upload', models.ImageField(help_text='загрузите картинку', upload_to='uploads/preview/%Y/%m', verbose_name='картинка')),
                ('landmark', models.OneToOneField(help_text='выберете достопримечательность', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='landmarks.landmarkitem', verbose_name='достопримечательность')),
            ],
            options={
                'verbose_name': 'фотографию достопримечательности',
                'verbose_name_plural': 'превьюшки достопримечательностей',
            },
        ),
        migrations.CreateModel(
            name='LandmarkItemGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.ImageField(help_text='загрузите картинку', upload_to='uploads/gallery/%Y/%m', verbose_name='картинка')),
                ('landmark', models.ForeignKey(help_text='выберете достопримечательность', on_delete=django.db.models.deletion.CASCADE, to='landmarks.landmarkitem', verbose_name='достопримечательность')),
            ],
            options={
                'verbose_name': 'фотографию достопримечательности',
                'verbose_name_plural': 'фотогалерея достопримечательностей',
            },
        ),
    ]
